name: Lighthouse Desktop Config

on:
  schedule:
    - cron: '0 13 * * 1'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://thnkrn.vercel.app/
          runs: 1
          configPath: '.github/lighthouse/custom-config/lighthouserc-desktop-config.json'
          uploadArtifacts: true
