name: Lighthouse Budget

on:
  schedule:
    - cron: '*/180 * * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://thnkrn.vercel.app/
          runs: 1
          budgetPath: '.github/lighthouse/budget/budget.json'
          uploadArtifacts: true
